"""
src/shared/reporting.py
=======================
Orchestrator-facing reporting helpers that turn the leak-free primitives in
``quality_metrics`` into the supplementary artefacts an *Analyst* submission
requires. Both ``standard`` and ``r_comparable`` run_analysis modules call these,
so the QC and benchmarking outputs are generated by one implementation.

Two entry points:

  * ``run_quality_control``      — technical %CV, biological %CV and Broadhurst
                                   D-ratio computed on the LINEAR normalised
                                   matrix, written as a per-feature table plus a
                                   study-level summary.
  * ``run_classification_benchmark`` — pooled leave-one-colony-out out-of-fold
                                   predictions per classifier, reduced to macro-F1,
                                   per-class recall/precision and a publication-
                                   ready confusion-matrix figure.

Every threshold, aggregate and export toggle is read from the passed ``config``
module, so behaviour is controlled entirely from ``config.py`` / ``config.json``.
"""

import contextlib
import os
import warnings

import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

from shared.quality_metrics import (technical_cv, biological_cv, dispersion_ratio,
                                     grouped_oof_predictions, classification_metrics,
                                     plot_confusion_matrix)
from shared.classifier_comparison_standard import small_sample_guards


@contextlib.contextmanager
def _suppress_allnan():
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', r'.*(All-NaN|Mean of empty).*', RuntimeWarning)
        yield


def _finite_fraction(values, threshold):
    """Fraction of finite entries at or below ``threshold`` (NaN if none finite)."""
    finite = values[np.isfinite(values)]
    return float((finite <= threshold).mean()) if finite.size else float('nan')


# ---------------------------------------------------------------------------------
# 1. Quality control (analytical reproducibility)
# ---------------------------------------------------------------------------------

def run_quality_control(X_linear, mz, groups, y_labels, out_dir, safe_name, config,
                        log=print):
    """
    Compute and persist per-feature analytical-QC metrics.

    Parameters
    ----------
    X_linear : ndarray (n_samples, n_features)
        LINEAR normalised intensities — normalisation applied but BEFORE any
        log/glog transform or scaling (e.g. ``preprocess(..., return_stages=True)
        ['normalized']`` or ``normalize_only(...)``). Coefficient of variation is
        only meaningful on this scale; ``quality_metrics`` raises on transformed
        input.
    mz : array-like (n_features,)          m/z label per feature.
    groups : array-like (n_samples,)       colony (biological-unit) id per sample;
                                           technical replicates share an id.
    y_labels : array-like (n_samples,)     condition label per sample.
    out_dir : str                          supplementary output directory.
    safe_name : str                        filesystem-safe experiment name.
    config : module                        pipeline configuration.

    Returns
    -------
    (per_feature_table, summary) : (pandas.DataFrame, dict)
    """
    aggregate = getattr(config, 'QC_AGGREGATE', 'median')
    min_reps = getattr(config, 'MIN_TECH_REPLICATES', 2)
    cv_accept = float(getattr(config, 'CV_ACCEPT_PCT', 30.0))
    cv_strict = float(getattr(config, 'CV_STRICT_PCT', 20.0))
    dratio_accept = float(getattr(config, 'DRATIO_ACCEPT_PCT', 50.0))

    tcv = technical_cv(X_linear, groups, aggregate=aggregate,
                       min_reps=min_reps)['per_feature']
    bcv = biological_cv(X_linear, groups, class_labels=y_labels,
                        aggregate=aggregate)['per_feature']
    dratio = dispersion_ratio(X_linear, groups, class_labels=y_labels)['per_feature']

    pass_cv = tcv <= cv_accept
    pass_dratio = dratio <= dratio_accept
    table = pd.DataFrame({
        'mz': np.asarray(mz, dtype=float),
        'technical_cv_pct': tcv,
        'biological_cv_pct': bcv,
        'dratio_pct': dratio,
        'pass_cv': pass_cv,
        'pass_dratio': pass_dratio,
        'pass_both': pass_cv & pass_dratio,
    })

    with _suppress_allnan():
        summary = {
            'n_features': int(table.shape[0]),
            'aggregate': aggregate,
            'median_technical_cv_pct': float(np.nanmedian(tcv)),
            'median_biological_cv_pct': float(np.nanmedian(bcv)),
            'median_dratio_pct': float(np.nanmedian(dratio)),
            f'frac_technical_cv_under_{int(cv_strict)}pct': _finite_fraction(tcv, cv_strict),
            f'frac_technical_cv_under_{int(cv_accept)}pct': _finite_fraction(tcv, cv_accept),
            f'frac_dratio_under_{int(dratio_accept)}pct': _finite_fraction(dratio, dratio_accept),
            'n_pass_both': int(np.nansum((pass_cv & pass_dratio).astype(float))),
        }

    if getattr(config, 'EXPORT_QC_TABLE', True):
        os.makedirs(out_dir, exist_ok=True)
        feat_path = os.path.join(out_dir, f'qc_features_{safe_name}.csv')
        table.to_csv(feat_path, index=False, encoding='utf-8')
        log(f"  Saved QC feature table -> {feat_path}")
        summary_path = os.path.join(out_dir, f'qc_summary_{safe_name}.csv')
        pd.DataFrame([summary]).to_csv(summary_path, index=False, encoding='utf-8')
        log(f"  Saved QC summary       -> {summary_path}")

    return table, summary


# ---------------------------------------------------------------------------------
# 2. Classification benchmarking (multi-class)
# ---------------------------------------------------------------------------------

def _estimator_factories(enabled_names, n_biological, random_state):
    """Estimator constructors matching the reported grouped-CV classifiers.

    The small-sample capacity guards are applied identically to the CV path
    (``small_sample_guards``), so the benchmark reflects the same models whose
    accuracies are reported.
    """
    g = small_sample_guards(n_biological)
    gb_params = dict(n_estimators=100, learning_rate=0.1, max_depth=3)
    gb_params.update(g['gb'])
    factories = {
        'Random Forest': lambda: RandomForestClassifier(
            n_estimators=100, random_state=random_state, **g['rf']),
        'SVM': lambda: SVC(kernel='linear', random_state=random_state, **g['svm']),
        'Gradient Boosting': lambda: GradientBoostingClassifier(
            random_state=random_state, **gb_params),
        'Logistic Regression': lambda: LogisticRegression(
            max_iter=1000, random_state=random_state, **g['logreg']),
        'LDA': lambda: LinearDiscriminantAnalysis(),
        'Ridge': lambda: RidgeClassifier(**g['ridge']),
    }
    return {name: factories[name] for name in enabled_names if name in factories}


def run_classification_benchmark(X_binned, y_labels, groups, prep_steps, n_splits,
                                 enabled_names, out_dir, safe_name, experiment_name,
                                 config, log=print):
    """
    Pooled leave-one-colony-out out-of-fold benchmark for each enabled classifier.

    For every classifier a single ``StratifiedGroupKFold`` partition produces
    leak-free pooled OOF predictions (the same per-fold preprocessing pipeline as
    the accuracy path), which are reduced to macro-F1, weighted-F1, accuracy,
    balanced accuracy and per-class recall/precision, plus an *Analyst*-standard
    confusion-matrix figure. ``X_binned`` must be the RAW binned matrix.

    Returns
    -------
    pandas.DataFrame  one row per classifier with the scalar metrics and the
                      per-class recall/precision columns.
    """
    n_biological = len(np.unique(groups))
    random_state = int(getattr(config, 'RANDOM_SEED', 42))
    factories = _estimator_factories(enabled_names, n_biological, random_state)
    if not factories:
        log("  [benchmark] no enabled classifiers — skipped")
        return pd.DataFrame()

    le = LabelEncoder()
    y_enc = le.fit_transform(y_labels)
    class_names = [str(c) for c in le.classes_]

    export_cm = getattr(config, 'EXPORT_CONFUSION_MATRIX', True)
    normalize_cm = getattr(config, 'CONFUSION_MATRIX_NORMALIZE', True)
    if export_cm:
        os.makedirs(out_dir, exist_ok=True)

    rows = []
    for name, factory in factories.items():
        y_pred = grouped_oof_predictions(factory(), X_binned, y_enc, groups,
                                         prep_steps, n_splits,
                                         random_state=random_state)
        m = classification_metrics(y_enc, y_pred, class_names=class_names)
        row = {
            'classifier': name,
            'macro_f1': m['macro_f1'],
            'weighted_f1': m['weighted_f1'],
            'accuracy': m['accuracy'],
            'balanced_accuracy': m['balanced_accuracy'],
        }
        for cls in class_names:
            row[f'recall_{cls}'] = m['per_class'][cls]['recall']
            row[f'precision_{cls}'] = m['per_class'][cls]['precision']
        rows.append(row)
        log(f"  {name:20s}  macro-F1={m['macro_f1']:.3f}  "
            f"balanced-acc={m['balanced_accuracy']:.3f}")

        if export_cm:
            cm_name = name.replace(' ', '_')
            cm_path = os.path.join(out_dir,
                                   f'confusion_matrix_{safe_name}_{cm_name}.png')
            plot_confusion_matrix(m['confusion'], m['labels'], cm_path,
                                  title=f'{name} — {experiment_name}',
                                  normalize=normalize_cm)
            log(f"    confusion matrix -> {cm_path}")

    benchmark_df = pd.DataFrame(rows)
    if getattr(config, 'EXPORT_BENCHMARK_TABLE', True) and not benchmark_df.empty:
        os.makedirs(out_dir, exist_ok=True)
        bench_path = os.path.join(out_dir, f'classification_metrics_{safe_name}.csv')
        benchmark_df.to_csv(bench_path, index=False, encoding='utf-8')
        log(f"  Saved classification benchmark -> {bench_path}")
    return benchmark_df
